apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: envoy-front-proxy-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.namespace }}
      service: envoy-front-proxy
  policyTypes:
  - Ingress
  - Egress
  ingress:
{{- if .Values.traffic.allowAllInboundTrafficOnKeyServices}}
  - from: []
    # Allow ingress from ingress controller/nodeport
    ports:
    - port: 1080
{{- end}}
{{- range $rule := .Values.traffic.networkPolicies.ingresses }}
  - from:
{{ toYaml $rule.from | indent 4}}
    ports:
      port: 1080
{{- end }}
  egress:
  - to: []
    # Allow DNS resolution
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: tdm-api
    ports:
    - port: 8686
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: studio-api
    ports:
    - port: 8484
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: notebook
    ports:
    - port: 8888
    - port: 8282
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: minio
    ports:
    - port: 9000
    - port: 9001
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: grafana
    ports:
    - port: 3000
{{- if .Values.services.jupyterhub.enabled }}
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: jupyterhub-proxy
    ports:
    - port: 8000
{{- end }}
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: flow-ui
    ports:
    - port: 5000
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: telegraf
    ports:
    - port: 8186
