apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flow-ui-network-policy
  namespace: {{ .Values.namespace }}
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to: []
  - ports:
    - port: 8484
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: studio-api
  - ports:
    - port: 8686
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: tdm-api
  - ports:
    - port: 8186
    - port: 8125
      protocol: UDP
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: telegraf
  ingress:
{{- if .Values.traffic.allowAllInboundTrafficOnKeyServices}}
  - from: []
    ports:
    - port: 5000
{{- end}}
{{- range $rule := .Values.traffic.networkPolicies.ingresses }}
  - from:
{{ toYaml $rule.from | indent 4}}
    ports:
      port: 5000
{{- end }}
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: envoy-front-proxy
    ports:
    - port: 5000
  podSelector:
    matchLabels:
      project: {{ .Values.namespace }}
      service: flow-ui
  policyTypes:
  - Ingress
  - Egress
