{{- if .Values.services.jupyterhub.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jupyterhub-singleuser-network-policy
  namespace: {{ .Values.namespace }}
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to: []
{{- if .Values.traffic.allowInternetAccess}}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/16
        - 172.16.0.0/20
{{- end }}
  - ports:
    - port: 8081
    to:
    - podSelector:
        matchLabels:
          project: {{ .Values.namespace }}
          service: jupyterhub
  ingress:
  - from:
    - podSelector:
        matchLabels:
          hub.jupyter.org/network-access-singleuser: 'true'
    ports:
    - port: notebook-port
  podSelector:
    matchLabels:
      app: jupyterhub
      component: singleuser-server
      release: jupyterhub
  policyTypes:
  - Ingress
  - Egress
{{- end }}