apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ray-head-network-policy
  namespace: {{ .Values.namespace }}
spec:
  egress:
  - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    to: []
{{- if .Values.traffic.allowInternetAccess}}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/16
        - 172.16.0.0/20
{{- end }}
  - ports: []
    to:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: ray-worker
  - ports: []
    to:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: tdm-api
  - ports:
      - port: 6379
    to:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: redis
  - ports:
      - port: 9000
      - port: 9001
    to:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: minio
  - ports:
      - port: 8186
      - port: 8125
        protocol: UDP
    to:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: telegraf
  - ports:
      - port: 5432
    to:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: db
  ingress:
  - ports: []
    from:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: tdm-api
  - ports: []
    from:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: engine
  - ports: []
    from:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: engine-tiny
  - ports: []
    from:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: model-trainer
  - ports: []
    from:
      - podSelector:
          matchLabels:
            project: {{ .Values.namespace }}
            service: ray-worker
  podSelector:
    matchLabels:
      project: {{ .Values.namespace }}
      service: ray-head
  policyTypes:
    - Ingress
    - Egress
