{{- if .Values.services.jupyterhub.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: jupyterhub-pdb
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      service: jupyterhub
{{- end }}