apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: model-trainer-pdb
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      service: model-trainer