apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    always-pinned: "1"
    service: ray-head
    project: {{ .Values.namespace }}
    snorkel.ai/ray-autoscaler-cluster: engine-ray
    snorkel.ai/ray-autoscaler-kind: head
    snorkel.ai/ray-autoscaler-type: ray-head
    snorkel.ai/compute-type: cpu
  name: ray-head
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      service: ray-head
      project: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        always-pinned: "1"
        service: ray-head
        project: {{ .Values.namespace }}
        snorkel.ai/ray-autoscaler-cluster: engine-ray
        snorkel.ai/ray-autoscaler-kind: head
        snorkel.ai/ray-autoscaler-type: ray-head
        snorkel.ai/compute-type: cpu
    spec:
{{- if .Values.affinity.binPackAlwaysPinnedPods }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: always-pinned
                operator: In
                values:
                - "0"
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
{{- end }}
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsUser: 99
        fsGroup: 99
{{- if .Values.services.jupyterhub.enabled }}
      serviceAccountName: snorkelflow-internal-k8s-rw-sa
{{- end }}
      containers:
      - env:
        - name: SERVICE_TYPE
          value: ray-head
        - name: SNORKEL_FLOW_VERSION
          value: "{{ .Values.version }}"
        - name: ENABLE_ROUTINE_ANALYZE
          value: "False"
        - name: DB_MINCONN
          value: "0"
        - name: DB_MAXCONN
          value: "0"
        - name: ENABLE_IPV6
          value: "False"
        - name: POD_AUTOSCALING_ENABLED
          value: "0"
        - name: RAY_WORKER_REPLICA_DEFAULT_COUNT
          value: "2"
        - name: RAY_GPU_WORKER_REPLICA_DEFAULT_COUNT
          value: "0"
        - name: LD_PRELOAD
          value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
        - name: MALLOC_CONF
          value: background_thread:true
        - name: MALLOC_MMAP_THRESHOLD_
          value: "16384"
        - name: CUPY_CACHE_DIR
          value: /var/lib/snorkel/.cupy-cache
        - name: SNORKELFLOW_MOUNT_DIR
          value: /data
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TDM_API_URL
          value: http://tdm-api:8686
        - name: REDIS_URL
          value: redis
        - name: MINIO_URL
          value: http://minio:9001
        - name: TELEGRAF_CADVISOR_URL
          value: telegraf:8186
        - name: TELEGRAF_URL
          value: http://telegraf:8125
        - name: TDM_CONN_STR
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: tdm_conn_str
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio_access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: minio_secret_key
        {{- if .Values.image.imageNames.engine }}
        image: {{ .Values.image.imageNames.engine }}
        {{- else if .Values.gpu.enabled }}
        image: snorkelai/engine:{{ .Values.version }}-cuda
        {{- else }}
        image: snorkelai/engine:{{ .Values.version }}
        {{- end }}
        name: ray-head
        args:
        - ray-head
        - --ray-dashboard-enabled=True
        ports:
          - containerPort: 7379
          - containerPort: 8265
          - containerPort: 10001
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/auth/jwt
          name: jwt-key-pub
        - mountPath: /dev/shm
          name: dshm
        resources:
          requests:
            memory: 16.0Gi
            cpu: "2.0"
          limits:
            memory: 16.0Gi
            cpu: "2.0"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.namespace }}-data
      - name: jwt-key-pub
        secret:
          secretName: jwt-key-pub
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 10000Mi
