apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    always-pinned: "0"
    project: {{ .Values.namespace }}
    service: studio-dask
    snorkel.ai/compute-type: cpu
  name: studio-dask
  namespace: {{ .Values.namespace }}
spec:
  replicas: 0
  selector:
    matchLabels:
      project: {{ .Values.namespace }}
      service: studio-dask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        always-pinned: "0"
        project: {{ .Values.namespace }}
        service: studio-dask
        snorkel.ai/compute-type: cpu
    spec:
{{- if .Values.affinity.binPackAlwaysPinnedPods }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: always-pinned
                operator: In
                values:
                - "1"
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
{{- end }}
      containers:
      - args:
        - api
        - --port
        - '0'
        - --mode
        - dask
        - --host
        - 0.0.0.0
        env:
        - name: SERVICE_TYPE
          value: studio-dask
        - name: IS_GPU_ENABLED
          value: "0"
        - name: DDF_CACHE_WORKERS
          value: '0'
        - name: DDF_CACHE_THREADS
          value: '0'
        - name: ENABLE_IPV6
          value: "False"
        - name: LD_PRELOAD
          value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
        - name: MALLOC_CONF
          value: background_thread:true
        - name: MALLOC_MMAP_THRESHOLD_
          value: '16384'
        - name: SNORKELFLOW_MOUNT_DIR
          value: /data
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MINIO_URL
          value: http://minio:9001
        - name: TELEGRAF_CADVISOR_URL
          value: telegraf:8186
        - name: TELEGRAF_URL
          value: http://telegraf:8125
        - name: STUDIO_API_URL
          value: http://studio-api:8484
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: minio_access_key
              name: minio-secret
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: minio_secret_key
              name: minio-secret
        {{- if .Values.image.imageNames.studio }}
        image: {{ .Values.image.imageNames.studio }}
        {{- else if .Values.gpu.enabled }}
        image: snorkelai/studio-api:{{ .Values.version }}-cuda
        {{- else }}
        image: snorkelai/studio-api:{{ .Values.version }}
        {{- end }}
        name: studio-dask
        ports: []
        resources:
{{- if .Values.services.studioDask.resources }}
{{ toYaml .Values.services.studioDask.resources | indent 10 }}
{{- else }}
          limits:
            cpu: '0.25'
            memory: 1.0Gi
          requests:
            cpu: '0.25'
            memory: 1.0Gi
{{- end }}
        volumeMounts:
        - mountPath: /data
          name: data
      imagePullSecrets:
      - name: regcred
      securityContext:
        fsGroup: 99
        runAsUser: 99
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.namespace }}-data
