apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    always-pinned: "0"
    service: telegraf
    project: {{ .Values.namespace }}
    snorkel.ai/compute-type: cpu
  name: telegraf
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      service: telegraf
      project: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        always-pinned: "0"
        service: telegraf
        project: {{ .Values.namespace }}
        snorkel.ai/compute-type: cpu
    spec:
{{- if .Values.affinity.binPackAlwaysPinnedPods }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: always-pinned
                operator: In
                values:
                - "1"
            topologyKey: kubernetes.io/hostname
            namespaceSelector: {}
{{- end }}
      imagePullSecrets:
        - name: regcred
      securityContext:
        fsGroup: 99
        runAsUser: 99
      containers:
      - env:
        - name: SERVICE_TYPE
          value: telegraf
        - name: TELEGRAF_CADVISOR_URL
          value: localhost:8186
        - name: POD_NAME
          valueFrom:
           fieldRef:
             fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TDM_CONN_STR
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: tdm_conn_str
        - name: REDIS_URL
          value: redis
        - name: TDM_API_URL
          value: http://tdm-api:8686
        - name: ENVOY_FRONT_PROXY_URL
          value: http://envoy-front-proxy:9901
        - name: INFLUXDB_V2_URL
          value: http://influxdb:8086
        - name: INFLUXDB_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: influxdb_access_key
        - name: INFLUXDB_BUCKET
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: influxdb_bucket
        {{- if .Values.image.imageNames.telegraf }}
        image: {{ .Values.image.imageNames.telegraf }}
        {{- else }}
        image: snorkelai/telegraf:1.21.4n
        {{- end }}
        name: telegraf
        ports:
        - containerPort: 8125
        - containerPort: 9273
        - containerPort: 8186
        volumeMounts:
        - name: telegraf
          mountPath: /etc/telegraf
        resources:
          requests:
            memory: 2.0Gi
            cpu: "1.0"
          limits:
            memory: 2.0Gi
            cpu: "1.0"
        readinessProbe:
          httpGet:
            path: /ping
            port: 8186
          initialDelaySeconds: 3
          periodSeconds: 30
      volumes:
        - name: telegraf
          configMap:
            name: telegraf
