{{- if and .Values.traffic.ingresses.services.minioApi.enabled (not .Values.traffic.istio.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.namespace }}-minio-api-ingress
  namespace: {{ .Values.namespace }}
{{- if or .Values.traffic.ingresses.annotations .Values.traffic.ingresses.services.minioApi.annotations }}
  annotations:
{{ toYaml (merge .Values.traffic.ingresses.services.minioApi.annotations .Values.traffic.ingresses.annotations) | indent 4 }}
{{- end }}
spec:
{{- if .Values.traffic.ingresses.ingressClassName }}
  ingressClassName: {{ .Values.traffic.ingresses.ingressClassName }}
{{- end }}
{{- if .Values.traffic.ingresses.tlsHosts }}
  tls:
  - hosts:
      - {{ .Values.traffic.ingresses.services.minioApi.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}
{{- end }}
  rules:
  - host: {{ .Values.traffic.ingresses.services.minioApi.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              number: 9001
        path: /
        pathType: Prefix
{{- end }}