{{- if .Values.services.secretsGenerator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: snorkel-secrets-generator
  namespace: {{ .Values.namespace }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - args:
        - generate-secrets
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SNORKELFLOW_HOSTNAME
          value: {{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}
        - name: SNORKEL_FLOW_VERSION
          value: "{{ .Values.version }}"
        {{- if .Values.image.imageNames.singleuserNotebook }}
        - name: SINGLEUSER_NOTEBOOK_BASE_IMAGE_NAME
          value: {{ .Values.image.imageNames.singleuserNotebook }}
        {{- end }}
        {{- if .Values.image.imageNames.secretsGenerator }}
        image: {{ .Values.image.imageNames.secretsGenerator }}
        {{- else }}
        image: snorkelai/secrets-generator:{{ .Values.version }}
        {{- end }}
        name: generate-secrets
      imagePullSecrets:
      - name: regcred
      serviceAccountName: {{ .Values.secretsGenerator.serviceAccount }}
      restartPolicy: Never
{{- end }}
