{{- if .Values.services.secretsGenerator.enabled }}
{{- if .Values.services.secretsGenerator.createRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snorkel-secrets-generator-cr
  namespace: {{ .Values.projectName }}
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snorkel-secrets-generator-sa
  namespace: {{ .Values.projectName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  snorkel-secrets-generator-cr
  namespace: {{ .Values.projectName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: snorkel-secrets-generator-cr
subjects:
- kind: ServiceAccount
  name: snorkel-secrets-generator-sa
  namespace: {{ .Values.projectName }}
---
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: snorkel-secrets-generator
  namespace: {{ .Values.namespace }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - args:
        - generate-secrets
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SNORKELFLOW_HOSTNAME
          value: {{ .Values.traffic.ingresses.services.snorkelflow.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}
        - name: SNORKEL_FLOW_VERSION
          value: "{{ .Values.version }}"
        {{- if .Values.image.imageNames.singleuserNotebook }}
        - name: SINGLEUSER_NOTEBOOK_BASE_IMAGE_NAME
          value: {{ .Values.image.imageNames.singleuserNotebook }}
        {{- end }}
        {{- if .Values.image.imageNames.secretsGenerator }}
        image: {{ .Values.image.imageNames.secretsGenerator }}
        {{- else }}
        image: snorkelai/secrets-generator:{{ .Values.version }}
        {{- end }}
        name: generate-secrets
      imagePullSecrets:
      - name: regcred
      {{- if .Values.services.secretsGenerator.createRole }}
      serviceAccountName: snorkel-secrets-generator-sa
      {{ - else }}
      serviceAccountName: {{ .Values.secretsGenerator.serviceAccount }}
      {{- end }}
      restartPolicy: Never
{{- end }}
