apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
    project: {{ .Values.namespace }}
  name: db
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    service: db
