apiVersion: v1
kind: Service
metadata:
  labels:
    service: flow-ui
    project: {{ .Values.namespace }}
  name: flow-ui
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.traffic.ingresses.serviceType }}
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: flow-ui
