apiVersion: v1
kind: Service
metadata:
  labels:
    service: grafana
    project: {{ .Values.namespace }}
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.traffic.ingresses.serviceType }}
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: grafana
