apiVersion: v1
kind: Service
metadata:
  labels:
    service: influxdb
    project: {{ .Values.namespace }}
  name: influxdb
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.traffic.ingresses.serviceType }}
  ports:
  - name: "8086"
    port: 8086
    targetPort: 8086
  selector:
    service: influxdb
