apiVersion: v1
kind: Service
metadata:
  labels:
    service: minio
    project: {{ .Values.namespace }}
  name: minio
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.traffic.ingresses.serviceType }}
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    service: minio
