apiVersion: v1
kind: Service
metadata:
  labels:
    project: {{ .Values.namespace }}
    service: model-registry
  name: model-registry
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: '2702'
    port: 2702
    targetPort: 2702
  selector:
    service: model-registry
  {{ if .Values.enablePublicServiceAndIngress }}
  type: NodePort
  {{ else }}
  type: ClusterIP
  {{ end }}
