apiVersion: v1
kind: Service
metadata:
  labels:
    service: notebook
    project: {{ .Values.namespace }}
  name: notebook
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.traffic.ingresses.serviceType }}
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  - name: "8282"
    port: 8282
    targetPort: 8282
  selector:
    service: notebook
