apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
    project: {{ .Values.namespace }}
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  {{ if .Values.enablePublicServiceAndIngress }}
  type: NodePort
  {{ else }}
  type: ClusterIP
  {{ end }}
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    service: redis
