apiVersion: v1
kind: Service
metadata:
  labels:
    service: studio-api
    project: {{ .Values.namespace }}
  name: studio-api
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.traffic.ingresses.serviceType }}
  ports:
  - name: "8484"
    port: 8484
    targetPort: 8484
  - name: "12500"
    port: 12500
    targetPort: 12500
  selector:
    service: studio-api
