apiVersion: v1
kind: Service
metadata:
  labels:
    service: telegraf
    project: {{ .Values.namespace }}
  name: telegraf
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: "8125"
    port: 8125
    targetPort: 8125
    protocol: "UDP"
  - name: "9273"
    port: 9273
    targetPort: 9273
  - name: "8186"
    port: 8186
    targetPort: 8186
  selector:
    service: telegraf
