{{- if and .Values.traffic.istio.enabled .Values.traffic.ingresses.services.minioApi.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.namespace }}-minio-api-vs
  namespace: {{ .Values.namespace }}
{{- if .Values.traffic.ingresses.services.minioApi.annotations }}
  annotations:
{{ toYaml .Values.traffic.ingresses.services.minioApi.annotations | indent 4 }}
{{- end }}
spec:
  gateways:
{{- if .Values.traffic.istio.gateway.create }}
  - {{ .Values.namespace }}/{{ .Values.namespace }}-gateway
{{- else }}
  - {{ .Values.traffic.istio.gateway.namespace }}/{{ .Values.traffic.istio.gateway.name }}
{{- end }}
  hosts:
  - {{ .Values.traffic.ingresses.services.minioApi.urlPrefix }}.{{ .Values.traffic.ingresses.domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: minio
        port:
          number: 9001
{{- end }}
