{{- if .Values.services.jupyterhub.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snorkelflow-internal-k8s-rw-sa-cr
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - secrets
  - configmaps
  - namespaces
  - endpoints
  - services
  - services/status
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  - extensions
  - networking.k8s.io
  - policy
  resources:
  - deployments
  - deployments/status
  - deployments/scale
  - networkpolicies
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
{{- end }}