{{- if .Values.services.jupyterhub.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub-cr
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - get
  - watch
  - list
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - get
  - watch
  - list
{{- end }}