apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "0014M00002GIAKlQAP", "product_id": "snorkel-flow.endpoints.snorkelai-public.cloud.goog", "partner_name": "Snorkel AI"}'
spec:
  descriptor:
    type: snorkelflow
    version: "{{ .Values.version }}"
    description: |-
      The data-centric AI platform for automated data labeling, integrated model training and analysis, and enhanced domain expert collaboration.

      ## Support
      Please contact your Snorkel AI representative.
    maintainers:
    - name: Snorkel AI
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy Snorkel Flow'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/grafana/README.md
    notes: |-
      ## Access Snorkel Flow UI

      To connect to the Snorkel Flow UI, you can either expose a public service endpoint or keep it private, but connect
      from your local environment with `kubectl port-forward`.

      ## Forward Snorkel Flow port in local environment

      You can use port forwarding feature of `kubectl` to forward Snorkel Flow's port to your local
      machine. Run the following command in background:

      ```shell
      kubectl get pods --namespace {{ .Release.Namespace }}
      ```

      Find the `flow-ui` pod, and then execute the following command:

      ```shell
      kubectl port-forward --namespace {{ .Release.Namespace }} flow-ui-67dfb7d64b-msngq 5000
      ```
      Replace the exact name of the `flow-ui` pod with the actual name of the pod listed.

      Now you can access Snorkel Flow with `http://localhost:5000/`.

      ## Login to Snorkel Flow
      Upload the license provided to you and follow the instructions on screen to create user accounts.

  info:
  - name: Forward Snorkel Flow port locally
    value: kubectl port-forward --namespace {{ .Release.Namespace }} FLOW-UI-POD-NAME 5000
  - name: Snorkel Flow UI URL
    value: http://localhost:5000/
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  addOwnerRef: true
  componentKinds:
  - group: ''
    kind: PersistentVolumeClaim
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: apps
    kind: Deployment